rover:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  wheel_right_front_position_controller:
    type: effort_controllers/JointVelocityController
    joint: wheel_right_front_joint 
    pid: {p: 100.0, i: 0.01, d: 10.0}
  wheel_right_back_position_controller:
    type: effort_controllers/JointVelocityController
    joint: wheel_right_back_joint 
    pid: {p: 100.0, i: 0.01, d: 10.0}
  wheel_left_front_position_controller:
    type: effort_controllers/JointVelocityController
    joint: wheel_left_front_joint 
    pid: {p: 100.0, i: 0.01, d: 10.0}
  wheel_left_back_position_controller:
    type: effort_controllers/JointVelocityController
    joint: wheel_left_back_joint 
    pid: {p: 100.0, i: 0.01, d: 10.0}
